#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This wizard verifies issue 06 on the real VM: it copies the repo over SSH,
# runs provision.sh, captures secrets into the VM's chmod-600 env file,
# starts the app, verifies page+stream, then proves the re-run is idempotent.
# It runs from the repo root on the dev machine; your secrets go only to the
# VM's /opt/yt-radio/.env — never into the repo.

REMOTE_TMP="/tmp/yt-radio"
APP_DIR="/opt/yt-radio"

# ssh_vm "command..." — run on the VM as opc (sudo inside where needed).
# Uses the dedicated yt-radio key; SSH_KEY may override the path.
SSH_KEY="${SSH_KEY:-$HOME/.ssh/yt-radio}"
ssh_vm() {
  ssh -i "$SSH_KEY" -o IdentitiesOnly=yes \
      -o StrictHostKeyChecking=accept-new "$SSH_USER@$VM_IP" "$@"
}

# vm_env_upsert KEY VALUE — idempotent KEY=VALUE upsert in the VM's env file,
# preserving every other line (and comments), mode 600.
vm_env_upsert() {
  local key="$1" value="$2"
  ssh_vm "sudo python3 - '$APP_DIR/.env' '$key' '$value' <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); key, value = sys.argv[2], sys.argv[3]
lines = [l for l in p.read_text().splitlines() if not l.startswith(key + '=')]
lines.append(key + '=' + value)
p.write_text('\n'.join(lines) + '\n')
PY
sudo chmod 600 $APP_DIR/.env && sudo chown radio:radio $APP_DIR/.env"
}

TOTAL_STAGES=5

banner "Issue 06 VM verification — provision.sh on the live Oracle Linux 9 box"

# ── Stage 1: connectivity ─────────────────────────────────────────────────
stage "SSH connectivity to the VM"
say "The provisioning target. SSH keys must already be set up for this host"
say "(OCI instances use the key pair you chose at launch; user is opc)."
ask VM_IP "VM public IP:" 
[[ -n "$VM_IP" ]] || { warn "no IP given"; exit 1; }
ask SSH_USER "SSH user [Enter = opc]:"
SSH_USER=${SSH_USER:-opc}
step "Testing: ssh $SSH_USER@$VM_IP"
if ssh_vm 'echo connected: $(cat /etc/oracle-release)' 2>/dev/null; then
  say ""
  note "✓ VM reachable."
else
  warn "ssh failed. Check the IP, that the instance is running, and that"
  warn "the key works: ssh -i ~/.ssh/yt-radio $SSH_USER@$VM_IP. Fix, re-run."
  exit 1
fi

# ── Stage 2: copy repo + provision (~10 min) ──────────────────────────────
stage "Copy repo to VM and run provision.sh"
say "We ship a clean git archive of HEAD (tracked files only — no .git, no"
say "local .env, no cookies) to $REMOTE_TMP, then run the committed"
say "provision.sh. It installs EPEL/RPM Fusion/ffmpeg/nodejs, uv + Python"
say "3.13, the radio user, /opt/yt-radio, 2 GB swap, journald config, and"
say "seeds $APP_DIR/.env (chmod 600) from .env.template."
say "This takes about 10 minutes; output streams live. Re-runs are safe."
confirm "Start provisioning now?"
step "Archiving HEAD and copying to the VM..."
git archive HEAD | ssh_vm "rm -rf $REMOTE_TMP && mkdir -p $REMOTE_TMP && tar xf - -C $REMOTE_TMP"
say "✓ repo copied."
step "Running provision.sh (live output):"
say ""
ssh_vm "sudo $REMOTE_TMP/provision.sh" || {
  warn "provision.sh failed — scroll up for the error, fix, re-run this wizard."
  exit 1
}
say ""
note "✓ provisioning finished."

# ── Stage 3: secrets into the VM env file ─────────────────────────────────
stage "Secrets → VM env file (chmod 600)"
say "Values land only in $APP_DIR/.env on the VM. Enter keeps the value"
say "already offered (your local .env). Anything skipped keeps the template"
say "comment and runs direct/unalerted."
ask PLAYLIST_URL "YouTube playlist URL:"
vm_env_upsert PLAYLIST_URL "$PLAYLIST_URL"
BASE_URL_DEFAULT="http://$VM_IP:8000"
ask BASE_URL "Base URL [Enter = $BASE_URL_DEFAULT]:"
vm_env_upsert BASE_URL "${BASE_URL:-$BASE_URL_DEFAULT}"
say ""
say "DataImpulse residential proxy (leave both empty for direct mode):"
ask_secret DATAIMPULSE_USER "DataImpulse username:"
vm_env_upsert DATAIMPULSE_USER "$DATAIMPULSE_USER"
ask_secret DATAIMPULSE_PASS "DataImpulse password:"
vm_env_upsert DATAIMPULSE_PASS "$DATAIMPULSE_PASS"
say ""
say "Pause-alert email via Resend (all three empty = no alerting):"
ask_secret RESEND_API_KEY "Resend API key:"
vm_env_upsert RESEND_API_KEY "$RESEND_API_KEY"
ask ALERT_EMAIL_FROM "Alert email FROM:"
vm_env_upsert ALERT_EMAIL_FROM "$ALERT_EMAIL_FROM"
ask ALERT_EMAIL_TO "Alert email TO:"
vm_env_upsert ALERT_EMAIL_TO "$ALERT_EMAIL_TO"
step "Verifying env file mode/owner on the VM..."
ssh_vm "stat -c '%a %U:%G' $APP_DIR/.env"

# ── Stage 4: start the app, verify page + stream ──────────────────────────
stage "Start the app manually and verify it streams"
say "The issue-06 demo: log in as radio, start the app directly (no nginx),"
say "and pull real audio off /stream. We run it in the background as radio"
say "and tail the log so you can see the proxied-mode banner."
confirm "Start the app on the VM now?"
ssh_vm "sudo pkill -f 'python yt_radio.py' 2>/dev/null || true; sleep 1;
sudo -iu radio bash -c 'cd $APP_DIR && nohup uv run python yt_radio.py >/tmp/radio.log 2>&1 &'
sleep 8; tail -n 15 /tmp/radio.log" || true
step "Checking the page (loopback)..."
ssh_vm "curl -sSf http://localhost:8000/ >/dev/null && echo 'page-ok' || echo 'page-FAIL'"
step "Checking the stream: pulling ≥64 KB of audio..."
ssh_vm "curl -sSf http://localhost:8000/stream --max-time 60 | head -c 65536 > /tmp/stream.bin; ls -l /tmp/stream.bin; head -c 4 /tmp/stream.bin | od -c | head -1" || true
say "A ~65536-byte file means the stream plays. If it's short, check"
say "/tmp/radio.log on the VM (playlist URL? proxy creds? bot-wall?)."
pause "Stream verified visually?"

# ── Stage 5: idempotent re-run ────────────────────────────────────────────
stage "Re-run provision.sh — must succeed untouched"
say "The reclaimed-VM promise: re-running provision.sh completes cleanly,"
say "keeps your .env edits, and never duplicates swap/fstab/user entries."
confirm "Re-run provisioning now?"
ssh_vm "sudo $REMOTE_TMP/provision.sh" || {
  warn "re-run FAILED — idempotency bug. Paste the output to the agent."
  exit 1
}
step "Checking invariants after the re-run..."
ssh_vm "echo '--- user (expect one line)'; sudo getent passwd radio
echo '--- fstab swap lines (expect 1)'; grep -c '^/swapfile' /etc/fstab
echo '--- swap active'; swapon --show
echo '--- swappiness'; cat /proc/sys/vm/swappiness
echo '--- env file survived (mode/owner + your playlist)'; stat -c '%a %U:%G' $APP_DIR/.env; sudo grep -c '^PLAYLIST_URL=' $APP_DIR/.env
echo '--- journald drop-in'; cat /etc/systemd/journald.conf.d/radio.conf"
say ""
say "App may have been killed by nothing — but if the stream check matters,"
say "the app is still running as radio (re-run does not touch processes)."
pause "All invariants look right?"

finish

cat <<'EOF'

  Issue 06 verification done. Next:
    - Tell the agent the results — the two open checkboxes get ticked and
      issue 06 moves to done.
    - The app is still running on the VM (stop it with:
      ssh opc@VM_IP "sudo pkill -f 'python yt_radio.py'").
    - Issue 07 (gunicorn/nginx/TLS) builds on this — DNS, OCI ingress and
      Resend sender verification come next.
EOF
